# Generated by Django 6.1 on 2026-08-17 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0002_remove_utilisateur_mot_de_passe_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneappro',
            name='prix_lot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ligneappro',
            name='quantite_par_lot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
