# Generated by Django 6.1 on 2026-08-17 18:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0003_ligneappro_prix_lot_ligneappro_quantite_par_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncaisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('credit', 'Crédit client')], max_length=20),
        ),
        migrations.CreateModel(
            name='AjustementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('motif', models.CharField(choices=[('perte', 'Perte'), ('casse', 'Casse'), ('vol', 'Vol'), ('comptage', 'Comptage physique'), ('erreur', 'Erreur de saisie'), ('autre', 'Autre')], max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='RemboursementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
        ),
    ]
