# Generated by Django 6.1 on 2026-08-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0004_alter_transactioncaisse_mode_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
