# Generated by Django 6.1 on 2026-08-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0006_client_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='permissions_supplementaires',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
