# Generated by Django 6.1 on 2026-08-18 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0007_utilisateur_permissions_supplementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='unite_vente',
            field=models.CharField(choices=[('unite', 'Unité'), ('kg', 'Kilogramme')], default='unite', max_length=10),
        ),
        migrations.AlterField(
            model_name='ajustementstock',
            name='delta',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ligneappro',
            name='quantite_par_lot',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='ligneappro',
            name='quantite_recue',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil_alerte',
            field=models.DecimalField(decimal_places=3, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
