# Generated by Django 6.1 on 2026-08-25 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0008_produit_unite_vente_alter_ajustementstock_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_vente_gros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_gros',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.001)]),
        ),
        migrations.AddField(
            model_name='venteproduits',
            name='reduction_montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
