# Generated by Django 6.1 on 2026-08-25 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0009_vente_en_gros_et_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('tranche', 'Tranche (paiement partiel)'), ('credit', 'Crédit fournisseur')], default='comptant', max_length=20),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='solde_du',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        # Toutes les tables de cette base (y compris superette_fournisseur et
        # superette_utilisateur, référencées ci-dessous) sont en MyISAM, un
        # moteur qui ne supporte pas les contraintes FOREIGN KEY — aucune
        # table de l'app n'en a jamais eu, l'intégrité référentielle est
        # gérée uniquement côté ORM Django (on_delete=PROTECT). Le moteur
        # par défaut de ce serveur MySQL est InnoDB : sans ce SET, la table
        # créée ci-dessous serait InnoDB et Django échouerait à ajouter les
        # FK (erreur 1824, "Failed to open the referenced table") puisque
        # InnoDB exige que la table référencée le soit aussi. SET (sans
        # GLOBAL) ne modifie que la session courante.
        migrations.RunSQL(
            "SET default_storage_engine = 'MyISAM'",
            reverse_sql="SET default_storage_engine = 'InnoDB'",
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
        ),
        migrations.RunSQL(
            "SET default_storage_engine = 'InnoDB'",
            reverse_sql="SET default_storage_engine = 'MyISAM'",
        ),
    ]
