# Generated by Django 6.1 on 2026-08-25 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0009_vente_en_gros_et_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='mode_paiement',
            field=models.CharField(choices=[('comptant', 'Comptant'), ('tranche', 'Tranche (paiement partiel)'), ('credit', 'Crédit fournisseur')], default='comptant', max_length=20),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='solde_du',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
        ),
    ]
