# Generated by Django 6.1 on 2026-08-26 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0010_paiement_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('fond_ouverture', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('montant_compte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_attendu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10)),
                ('commentaire_fermeture', models.CharField(blank=True, max_length=255)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='superette.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='transactioncaisse',
            name='session_caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='superette.sessioncaisse'),
        ),
        migrations.AddIndex(
            model_name='sessioncaisse',
            index=models.Index(fields=['utilisateur', 'statut'], name='superette_s_utilisa_d5d56f_idx'),
        ),
    ]
