# Generated by Django 6.1 on 2026-08-26 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0011_session_caisse'),
    ]

    operations = [
        # Voir 0011_session_caisse.py pour l'explication complète : toutes
        # les tables de cette base sont en MyISAM (aucune contrainte FK
        # réelle), mais le moteur par défaut du serveur MySQL est InnoDB —
        # sans ce SET, ces deux nouvelles tables seraient InnoDB et leurs
        # ADD CONSTRAINT vers des tables MyISAM échoueraient (erreur 1824).
        migrations.RunSQL(
            "SET default_storage_engine = 'MyISAM'",
            reverse_sql="SET default_storage_engine = 'InnoDB'",
        ),
        migrations.CreateModel(
            name='RetourVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('affecte_caisse', models.BooleanField(default=False)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('session_caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='superette.sessioncaisse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='superette.transactioncaisse')),
            ],
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('ligne_vente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='superette.lignevente')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='superette.retourvente')),
            ],
        ),
        migrations.RunSQL(
            "SET default_storage_engine = 'InnoDB'",
            reverse_sql="SET default_storage_engine = 'MyISAM'",
        ),
    ]
