# Generated by Django 6.1 on 2026-08-26 21:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0012_retour_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncaisse',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('credit', 'Crédit client'), ('mixte', 'Paiement mixte')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaiementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('credit', 'Crédit client'), ('mixte', 'Paiement mixte')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='superette.transactioncaisse')),
            ],
        ),
    ]
