# Generated by Django 6.1 on 2026-08-28 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0013_paiement_vente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCreanceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('total_mis_a_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rembourse', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives_creance', to='superette.client')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
            options={
                'ordering': ['-date_archivage'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveCreanceFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_archivage', models.DateTimeField(auto_now_add=True)),
                ('total_recu_a_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives_creance', to='superette.fournisseur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
            options={
                'ordering': ['-date_archivage'],
            },
        ),
    ]
