# Generated by Django 6.1 on 2026-09-16 17:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0014_archivecreanceclient_archivecreancefournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='annulee',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RetourAppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('appro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='superette.approvisionnement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superette.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneRetourAppro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('ligne_appro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='superette.ligneappro')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='superette.retourappro')),
            ],
        ),
    ]
