# Generated by Django 6.1 on 2026-09-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superette', '0015_approvisionnement_annulee_retourappro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='est_compte_principal',
            field=models.BooleanField(default=False),
        ),
    ]
