# Generated by Django 5.2.17 on 2026-09-29 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superette", "0016_utilisateur_est_compte_principal"),
    ]

    operations = [
        migrations.AddField(
            model_name="remboursementcredit",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("wave", "Wave"),
                    ("orange_money", "Orange Money"),
                ],
                default="especes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="remboursementcredit",
            name="session_caisse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="remboursements_credit",
                to="superette.sessioncaisse",
            ),
        ),
        migrations.AddField(
            model_name="transactioncaisse",
            name="date_annulation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transactioncaisse",
            name="montant_annulation_especes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="transactioncaisse",
            name="session_annulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annulations",
                to="superette.sessioncaisse",
            ),
        ),
    ]
