# Generated by Django 5.2.17 on 2026-10-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superette", "0017_annulation_tracee_remboursement_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstantaneDonneesTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("donnees", models.JSONField()),
            ],
        ),
    ]
